### ISSUE TITLE
AttributeError: module 'lzf' has no attribute 'decompress'

### ISSUE THREAD

**Issue by syd-21** [jinzhengguang/RPEA#3]
python train.py --cfg ./jrdb19.yaml 
/media/bvb/SSD-2/jrd/RPEA/lib/jrdb_det3d_eval/jrdb_det3d_eval/eval.py:13: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
2024-11-14 16:37:17,885  DEBUG  Log directory: /media/bvb/SSD-2/jrd/RPEA/logs/unet_bl_voxel_jrdb_0.05_0.1_20241114_163717
2024-11-14 16:37:17,885  DEBUG  Backup ./jrdb19.yaml
2024-11-14 16:37:17,895   INFO  CUDA_VISIBLE_DEVICES=ALL
2024-11-14 16:37:17,896  DEBUG  Pipeline starts.
2024-11-14 16:37:17,979  DEBUG  Training starts.
train (0/40):   0%|                                     | 0/680 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 92, in <module>
    run_training(model, pipeline, cfg)
  File "train.py", line 18, in run_training
    status = pipeline.train(model, train_loader, val_loader)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/pipeline.py", line 19, in train
    status = self.trainer.train(model, train_loader, eval_loader)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/trainer.py", line 132, in train
    self._train_epoch(model, train_loader)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/trainer.py", line 247, in _train_epoch
    for ib, batch in enumerate(train_loader):
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/dataset_det3d.py", line 83, in __getitem__
    data_dict = self.__handle[idx]
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/jrdb_handle.py", line 73, in __getitem__
    "pc_upper": self.load_pointcloud(urls["pc_upper"]),
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/jrdb_handle.py", line 104, in load_pointcloud
    pc = point_cloud_from_path(url).pc_data
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 307, in point_cloud_from_path
    pc = point_cloud_from_fileobj(f)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 296, in point_cloud_from_fileobj
    pc_data = parse_binary_compressed_pc_data(f, dtype, metadata)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 264, in parse_binary_compressed_pc_data
    buf = lzf.decompress(compressed_data, uncompressed_size)
AttributeError: module 'lzf' has no attribute 'decompress'

**Comment by jinzhengguang** [comment]
> python train.py --cfg ./jrdb19.yaml /media/bvb/SSD-2/jrd/RPEA/lib/jrdb_det3d_eval/jrdb_det3d_eval/eval.py:13: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details. def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41): 2024-11-14 16:37:17,885 DEBUG Log directory: /media/bvb/SSD-2/jrd/RPEA/logs/unet_bl_voxel_jrdb_0.05_0.1_20241114_163717 2024-11-14 16:37:17,885 DEBUG Backup ./jrdb19.yaml 2024-11-14 16:37:17,895 INFO CUDA_VISIBLE_DEVICES=ALL 2024-11-14 16:37:17,896 DEBUG Pipeline starts. 2024-11-14 16:37:17,979 DEBUG Training starts. train (0/40): 0%| | 0/680 [00:00<?, ?it/s]Traceback (most recent call last): File "train.py", line 92, in run_training(model, pipeline, cfg) File "train.py", line 18, in run_training status = pipeline.train(model, train_loader, val_loader) File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/pipeline.py", line 19, in train status = self.trainer.train(model, train_loader, eval_loader) File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/trainer.py", line 132, in train self._train_epoch(model, train_loader) File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/trainer.py", line 247, in _train_epoch for ib, batch in enumerate(train_loader): File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise raise exception AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/dataset_det3d.py", line 83, in **getitem** data_dict = self.__handle[idx] File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/jrdb_handle.py", line 73, in **getitem** "pc_upper": self.load_pointcloud(urls["pc_upper"]), File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/jrdb_handle.py", line 104, in load_pointcloud pc = point_cloud_from_path(url).pc_data File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 307, in point_cloud_from_path pc = point_cloud_from_fileobj(f) File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 296, in point_cloud_from_fileobj pc_data = parse_binary_compressed_pc_data(f, dtype, metadata) File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/dataset/handles/_pypcd.py", line 264, in parse_binary_compressed_pc_data buf = lzf.decompress(compressed_data, uncompressed_size) AttributeError: module 'lzf' has no attribute 'decompress'

`pip install python-lzf==0.2.6`
